kind: Service
apiVersion: v1
metadata:
  name: netflix-clone-service
  namespace: netflix-clone
spec:
  selector:
    apps: netflix-clone
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP
